# Site settings
title: My Gamedev portfolio page
description: My Gamedev portfolio page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tobias Zengerle
user_description: TODO
user_title: Software Developer
email: tobi.zengerle@gmail.com
twitter_username: lorem_ipsum
github_username:  zengerleTo
gplus_username:  lorem_ipsum
photo: /assets/img/Bewerbungsfoto.jpg

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
